CREATE TABLE IF NOT EXISTS Status (
  Status_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Points INTEGER DEFAULT 0,
  Wins INTEGER DEFAULT 0,
  Loses INTEGER DEFAULT 0,
  Rank TEXT
);

CREATE TABLE IF NOT EXISTS Users (
  User_Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Nickname TEXT NOT NULL UNIQUE,
  Email TEXT NOT NULL UNIQUE,
  Password TEXT NOT NULL,
  Status_ID INTEGER,
  Avatar TEXT,
  FOREIGN KEY (Status_ID) REFERENCES Status(Status_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Keyword (
  Keyword_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Keyword TEXT NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_users_email ON Users(Email);
CREATE INDEX IF NOT EXISTS idx_users_nickname ON Users(Nickname);
CREATE INDEX IF NOT EXISTS idx_users_status ON Users(Status_ID);

